title: Olin College Software Design
description: Spring 2026
theme: just-the-docs

url: https://olincollege.github.io/softdes-material

aux_links:
  GitHub Repo: github.com/olincollege/softdes-2026-01
